name: build-and-package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Show Go env
        run: go env

      - name: Install fpm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ruby ruby-dev build-essential rpm
          sudo gem install --no-document fpm

      - name: Derive Version
        id: ver
        run: |
          ref_name='${{ github.ref_name }}'
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "version=$ref_name" >> $GITHUB_OUTPUT
          else
            short=$(git rev-parse --short HEAD)
            echo "version=main-$short" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - name: Build & Package
        env:
          VERSION: "${{ steps.ver.outputs.version }}"
          ARCH: ${{ matrix.arch }}
        run: |
          echo "Using version=$VERSION"
          bash package.sh

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: deb-${{ matrix.arch }}
          path: dist/*.deb

      - name: Upload rpm
        uses: actions/upload-artifact@v3
        with:
          name: rpm-${{ matrix.arch }}
          path: dist/*.rpm

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Display tree
        run: ls -R artifacts
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/**/*.deb
            artifacts/**/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}